version: '3.3'
services:

  api:
    environment:
      - YETI_REDIS_HOST=redis
      - YETI_REDIS_PORT=6379
      - YETI_REDIS_DATABASE=0
      - YETI_ARANGODB_HOST=arangodb
      - YETI_ARANGODB_PORT=8529
      - YETI_ARANGODB_DATABASE=yeti
      - YETI_ARANGODB_USERNAME=root
      - YETI_ARANGODB_PASSWORD=
      - YETI_AUTH_SECRET_KEY=SECRET
      - YETI_AUTH_ALGORITHM=HS256
      - YETI_AUTH_ACCESS_TOKEN_EXPIRE_MINUTES=30
      - YETI_AUTH_ENABLED=False
      - YETI_SYSTEM_PLUGINS_PATH=./plugins
      - YETI_EXPORT_PATH=${YETI_EXPORT_PATH:-/opt/yeti/exports}
    build:
      context: ./yeti/
      dockerfile: ./extras/docker/dev/Dockerfile
    image: yeti
    entrypoint:
      - /docker-entrypoint.sh
    command: ['envshell']
    ports:
      - 127.0.0.1:8000:8000
    depends_on:
      - redis
      - arangodb
    volumes:
      - /tmp/docker-yeti-exports:${YETI_EXPORT_PATH:-/opt/yeti/exports}
      - ./yeti/:/app/
    stdin_open: true # docker run -i
    tty: true        # docker run -t

  frontend:
    build:
      context: ./yeti-feeds-frontend/
      dockerfile: ./docker/dev/Dockerfile
    image: yeti-feeds-frontend
    ports:
      - 127.0.0.1:8080:8080
      - 127.0.0.1:3000:3000
    volumes:
      - ./yeti-feeds-frontend/:/app
    entrypoint:
      - /docker-entrypoint.sh
    command:
      - /bin/bash
    stdin_open: true # docker run -i
    tty: true        # docker run -t

  redis:
    image: redis:latest
    ports:
      - 127.0.0.1:6379:6379
    command: ["redis-server", "--save"]  # disable persistence


  arangodb:
    image: arangodb
    ports:
      - 127.0.0.1:8529:8529
    environment:
      - ARANGO_ROOT_PASSWORD=
