services:

  api:
    environment:
      - YETI_REDIS_HOST=redis
      - YETI_REDIS_PORT=6379
      - YETI_REDIS_DATABASE=0
      - YETI_ARANGODB_HOST=arangodb
      - YETI_ARANGODB_PORT=8529
      - YETI_ARANGODB_DATABASE=yeti
      - YETI_ARANGODB_USERNAME=root
      - YETI_ARANGODB_PASSWORD=
      - YETI_AUTH_SECRET_KEY=SECRET
      - YETI_AUTH_ALGORITHM=HS256
      - YETI_AUTH_ACCESS_TOKEN_EXPIRE_MINUTES=30
      - YETI_AUTH_BROWSER_TOKEN_EXPIRE_MINUTES=43200
      - YETI_AUTH_ENABLED=False
      - YETI_SYSTEM_PLUGINS_PATH=./plugins
      - YETI_AGENTS_ENABLED=${YETI_AGENTS_ENABLED:-False}
    build:
      context: ../../yeti/
      dockerfile: ./extras/docker/dev/Dockerfile
    image: yeti
    entrypoint: ["/bin/bash", "/docker-entrypoint.sh"]
    command: ['envshell']
    ports:
      - 127.0.0.1:8000:8000
    depends_on:
      redis:
        condition: service_started
      arangodb:
        condition: service_healthy
    volumes:
      - /tmp/docker-yeti-exports:/opt/yeti/exports
      - ../../yeti/:/app/
    stdin_open: true # docker run -i
    tty: true        # docker run -t

  frontend:
    build:
      context: ../../yeti-feeds-frontend/
      dockerfile: ./docker/dev/Dockerfile
    image: yeti-feeds-frontend
    ports:
      - 127.0.0.1:8080:8080
      - 127.0.0.1:3000:3000
    volumes:
      - ../../yeti-feeds-frontend/:/app
    entrypoint:
      - /docker-entrypoint.sh
    command:
      - /bin/bash
    stdin_open: true # docker run -i
    tty: true # docker run -t

  redis:
    image: redis:latest
    ports:
      - 127.0.0.1:6379:6379

  arangodb:
    image: arangodb:3.11
    ports:
      - 127.0.0.1:8529:8529
    environment:
      - ARANGO_ROOT_PASSWORD=
    healthcheck:
      test: ["CMD-SHELL", "arangosh --server.endpoint tcp://127.0.0.1:8529 --server.username root --server.password \"$$ARANGO_ROOT_PASSWORD\" --javascript.execute-string 'db._version()' >/dev/null 2>&1"]
      interval: 5s
      timeout: 5s
      start_period: 30s
      retries: 10

  # Microservices

  bloomcheck:
    container_name: bloomcheck
    image: yetiplatform/bloomcheck:dev
    entrypoint: [ '/app/bloomcheck', '-serve', '/bloomfilters' ]
    volumes:
      - /tmp/bloomfilters:/bloomfilters:ro

  agents:
    profiles: ["agents"]
    container_name: agents
    build:
      context: ../../yeti-agents/
    image: yetiplatform/yeti-agents:dev
    ports:
      - 127.0.0.1:8888:8888
    env_file:
      - ../../yeti-agents/.env
    volumes:
      - ../../yeti-agents/:/app
    entrypoint: [ "/bin/bash", "/app/entrypoint.sh" ]
    command: [ "manual" ]

  ollama:
    profiles: ["agents"]
    container_name: ollama
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama # Persist downloaded models
    # Uncomment the below if you have an NVIDIA GPU and the nvidia-container-toolkit installed
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]

volumes:
  ollama_data:
